### ISSUE TITLE
fix issue noticed from Wolfang

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/lifecontingencies#1]
I’m trying to reproduce the example given under the heading
Insurance and annuities on two heads in your Introduction to lifecontingencies Package, page 22, with my own data.
However, I get 2 different values:
axn(ActMannTables[[1]], x=100) + axn(ActFrauTables[[1]], x=102) - axyn(ActMannTables[[1]], ActFrauTables[[1]], x=100, y=102, status="joint", m=0)
# 5.928079849
axyzn(list(ActMannTables[[1]], ActFrauTables[[1]]), x=c(100, 102), status="last", m=0)
# 5.860986613
Shouldn’t they be the same?
Attached is the script. (10 different actuarial tables are created, but you can ignore that. Only the 2 actuarial tables for male and female with i=0.04 are used.)
The difference gets smaller if I reduce the age of x and y.
Kind regards from Hannover, Germany
Wolfgang Abele

ï»¿options(digits=10)
library(lifecontingencies)
male <- read.table(textConnection("MÃ¤nner  qx
0	0.000113
1	0.000113
2	0.000113
3	0.000113
4	0.000113
5	0.000113
6	0.000113
7	0.000113
8	0.000113
9	0.000113
10	0.000113
11	0.000113
12	0.000113
13	0.000114
14	0.000133
15	0.000175
16	0.000235
17	0.000309
18	0.000385
19	0.000447
20	0.000511
21	0.000617
22	0.000777
23	0.000786
24	0.000795
25	0.000804
26	0.000813
27	0.000814
28	0.000832
29	0.000863
30	0.000894
31	0.000934
32	0.000994
33	0.001063
34	0.001109
35	0.001112
36	0.001115
37	0.001118
38	0.001121
39	0.001145
40	0.001198
41	0.00128
42	0.001394
43	0.001521
44	0.001676
45	0.001864
46	0.002039
47	0.002201
48	0.002356
49	0.002516
50	0.002677
51	0.002831
52	0.003016
53	0.003258
54	0.003555
55	0.0039
56	0.004274
57	0.004676
58	0.005065
59	0.005422
60	0.005755
61	0.006102
62	0.006496
63	0.006971
64	0.007557
65	0.008293
66	0.009178
67	0.010137
68	0.011123
69	0.012169
70	0.013316
71	0.014649
72	0.016198
73	0.018056
74	0.020216
75	0.022646
76	0.025415
77	0.028511
78	0.031762
79	0.03547
80	0.03977
81	0.044321
82	0.04923
83	0.05454
84	0.060227
85	0.066281
86	0.072418
87	0.078658
88	0.085141
89	0.091502
90	0.098056
91	0.104216
92	0.11001
93	0.115695
94	0.121466
95	0.127386
96	0.133438
97	0.13958
98	0.145758
99	0.151914
100	0.158012
101	0.164479
102	0.170732
103	0.17674
104	0.182474
105	0.187907
106	0.193017
107	0.197785
108	0.202193
109	0.206228
110	0.209878
111	1"), as.is=TRUE, header=TRUE)

female <- read.table(textConnection("Frauen  qy
0	0.000059
1	0.000059
2	0.000059
3	0.000059
4	0.000059
5	0.000059
6	0.000059
7	0.000059
8	0.000059
9	0.000059
10	0.000059
11	0.000059
12	0.000059
13	0.000059
14	0.000059
15	0.000068
16	0.000085
17	0.00011
18	0.00011
19	0.00011
20	0.000111
21	0.000111
22	0.000111
23	0.000112
24	0.000112
25	0.000112
26	0.000112
27	0.000113
28	0.000118
29	0.000143
30	0.000202
31	0.000297
32	0.000357
33	0.000386
34	0.000404
35	0.000425
36	0.000449
37	0.000475
38	0.000507
39	0.000553
40	0.000622
41	0.000713
42	0.00079
43	0.000857
44	0.000929
45	0.001018
46	0.001117
47	0.001177
48	0.001202
49	0.001212
50	0.001231
51	0.001266
52	0.001324
53	0.001403
54	0.001491
55	0.001581
56	0.00167
57	0.001766
58	0.001866
59	0.001958
60	0.00206
61	0.002199
62	0.002383
63	0.002605
64	0.002885
65	0.003237
66	0.003661
67	0.004141
68	0.004637
69	0.005146
70	0.005698
71	0.006302
72	0.006994
73	0.007848
74	0.00889
75	0.010096
76	0.011504
77	0.0132
78	0.015135
79	0.017388
80	0.020117
81	0.023237
82	0.02674
83	0.030737
84	0.035271
85	0.040263
86	0.045997
87	0.052428
88	0.059507
89	0.067171
90	0.075313
91	0.083869
92	0.092315
93	0.100693
94	0.1089
95	0.116909
96	0.124725
97	0.132466
98	0.140118
99	0.147629
100	0.154934
101	0.163311
102	0.171514
103	0.179486
104	0.187179
105	0.194544
106	0.20154
107	0.208129
108	0.214281
109	0.219967
110	0.225167
111	1"), as.is=TRUE, header=TRUE)

Mann <- probs2lifetable(probs=male$qx, radix=100000, type="qx", name="Sterbetafel DAV 1994 R MÃ¤nner")
Frau <- probs2lifetable(probs=female$qy, radix=100000, type="qx", name="Sterbetafel DAV 1994 R MÃ¤nner")

i.rates <- c(0.04, 0.0325, 0.0275, 0.0225, 0.0175)
ActMannTables <- vector("list", 5) 
ActFrauTables <- vector("list", 5) 
for(i in seq_along(i.rates)) {
  ActMannTables[i] <- new("actuarialtable", x=Mann@x, lx=Mann@lx, interest=i.rates[i], name=paste0("Mann ", i-1))
  ActFrauTables[i] <- new("actuarialtable", x=Frau@x, lx=Frau@lx, interest=i.rates[i], name=paste0("Frau ", i-1))
}

axn(ActMannTables[[1]], x=100) + axn(ActFrauTables[[1]], x=102) - axyn(ActMannTables[[1]], ActFrauTables[[1]], x=100, y=102, status="joint", m=0) 
# 5.928079849
axyzn(list(ActMannTables[[1]], ActFrauTables[[1]]), x=c(100, 102), status="last", m=0)
# 5.860986613

**Comment by eschirmacher** [comment]
The code for **axyzn** with parameter **n** missing was ignoring the last term in the summation of v^k k_p_x.

The function has been updated to fix this issue and a test has been added.
