### ISSUE TITLE
Increasing geometrically axn and axyzn

### ISSUE THREAD

**Issue by Free-rider** [spedygiorgio/lifecontingencies#20]
Hello, 

Is there any way to calculate axn and azyzn with geometrically increasing? 

Thanks

**Comment by spedygiorgio** [comment]
Hi, as known from classical financial and actuarial mathematics, a geometrically increasing annuity can be priced using the synthetic interest rate $j=i-g$, being $i$ the discount rate and $g$ the geometric growth rate. I have added this clarification in the vignette. HTH
