### ISSUE TITLE
Macaulay Duration, Modified duration and Effective duration

### ISSUE THREAD

**Issue by nth1502** [spedygiorgio/lifecontingencies#21]
# ISSUE:
With reference to this source : https://www.investopedia.com/exam-guide/cfa-level-1/fixed-income-investments/effective-modified-macaulay-duration.asp

Current duratiion function in v1.3.2

_function (cashFlows, timeIds, i, k = 1, macaulay = TRUE) 
{
    out = 0
    if (missing(timeIds)) {
        warning("Warning: missing time vector")
        timeIds = 1
    }
    if (!(length(cashFlows) == length(timeIds))) 
        stop("Error! check dimensionality of cash flow and time ids vectors")
    interestRates = rep(i/k, length.out = length(timeIds))
    ts = timeIds * k
    v = (1 + interestRates)^-(ts)
    pv = sum((cashFlows * v))
    weightedTime = sum((cashFlows * v * ts))
    out = weightedTime/pv
    **if (macaulay == FALSE) 
        out = out
    else out = out/(1 + i/k)
    return(out)**
}_

Instead it should be 
**if (macaulay == TRUE) 
        out = out
    else out = out/(1 + i/k) 
    return(out)**

"Else" part in fact refers to Modified Duration, Not Effective Duration like documentation states (Although in some cases, Modified and Effective duration are the same)

#SUGGESTION:
1/Fixed the modified and effective duration in function and their documentation accordingly
2/Add another option of effective duration calculation.

**Comment by spedygiorgio** [comment]
Hi thanks for raising the issue. I have accepted your suggestion in the dev and I'll commit asap

**Comment by dutangc** [comment]
I have committed some modifications this afternoon. Feel free to commit.

Christophe

------------------------------------------------------------
Christophe Dutang
CEREMADE, Univ. Paris Dauphine, France
Web : http://dutangc.free.fr
------------------------------------------------------------

**Comment by nth1502** [comment]
Superb and prompt responses. Thank you for your attention!

**Comment by spedygiorgio** [comment]
added one duration test
